-- ============================================================
-- TELEGRAM GROUP CUSTOMER SUPPORT BOT DATABASE SCHEMA
-- Compatible with Supabase (PostgreSQL) and MySQL
-- ============================================================

-- 1. Support Groups Registry
CREATE TABLE IF NOT EXISTS support_groups (
    group_chat_id VARCHAR(100) PRIMARY KEY,
    group_title VARCHAR(255),
    is_active SMALLINT DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Conversations Table (Group Ticket Tracking)
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_chat_id VARCHAR(50) NOT NULL UNIQUE,
    customer_name VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Group Message Map (Maps Group Message ID to Customer Chat ID)
CREATE TABLE IF NOT EXISTS group_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_chat_id VARCHAR(100) NOT NULL,
    group_message_id BIGINT NOT NULL UNIQUE,
    customer_chat_id VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
